[package]
name = "lila-tablebase"
version = "0.1.0" # remember to update html_root_url
publish = false
description = "A Syzygy tablebase server"
homepage = "https://tablebase.lichess.org"
repository = "https://github.com/niklasf/lila-tablebase"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games"]
keywords = ["chess", "syzygy", "tablebase"]

[dependencies]
shakmaty = "0.6"
actix-web = "0.5"
actix = "0.5"
env_logger = "0.5"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = "2.31"
log = "0.4"

[dependencies.shakmaty-syzygy]
version = "0.3"
features = ["serde-1"]

[dependencies.arrayvec]
version = "0.4"
features = ["serde-1"]
