[package]
name = "lila-tablebase"
version = "0.1.0" # remember to update html_root_url
publish = false
description = "A Syzygy tablebase server"
homepage = "https://tablebase.lichess.org"
repository = "https://github.com/niklasf/lila-tablebase"
readme = "README.md"
license = "AGPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games"]
keywords = ["chess", "syzygy", "tablebase"]

[dependencies]
shakmaty = "0.12"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
structopt = "0.2"
gaviota-sys = "0.1"
rocket = "0.4.0-rc.1"
rocket_contrib = "0.4.0-rc.1"
env_logger = "0.6"

[dependencies.shakmaty-syzygy]
version = "0.9"
features = ["serde-1"]

[dependencies.arrayvec]
version = "0.4"
features = ["serde-1"]
